### ISSUE TITLE
Error when creating address

### ISSUE THREAD

**Issue by youssefgh** [coinables/coinables.github.io#1]
When opening the home page we have this error in console : `SyntaxError: missing } after function body`
the missing } is from the function btnCreate which causes the address creating to fail with : 
`ReferenceError: btnCreate is not defined`

**Comment by coinables** [comment]
Ah thank you, mistakenly removed on last commit. Been super busy all day and haven't checked it at all. Now fixed and pushed to master. Thanks for letting me know!

**Comment by youssefgh** [comment]
Cool ! super fast ! glad am the first one to discover a bug here 🥇 lol ! Thanks

**Comment by coinables** [comment]
Yea, the joys of opensource! What's your BTC address?

**Comment by youssefgh** [comment]
You're a nice guy since you have an open source spirit, i can't accept a donation from you ! i think the BitcoinJS team deserve it more than i do 👍 thank you
