### ISSUE TITLE
Generated Private Key does not contain my bitcoin transferred to 

### ISSUE THREAD

**Issue by johndhussey** [coinables/coinables.github.io#2]
hi, i used your website: coinables.github.io to generate a segwit address and corresponding private key. UI have transferred bitcoin to the segwit address generated but now am not able to access my bitcoin with the private key from your website. Can you please help!

**Comment by coinables** [comment]
"now am not able to access my bitcoin with the private key"
What wallet software are trying to use the private key with? Not all
wallets support segwit WIF private key import. SamouraiWallet supports
sweeping from segwit WIF keys.

**Comment by johndhussey** [comment]
Hi Kyle,

Thanks for your help. That Android app looks great. I ended up being able
to get access to my coins by using your website sweep functionality but in
IE. In Chrome it just didn't work for me.

So i have access to my coin again! That was a stressful moment :).

Cheers and have a good day.

**Comment by coinables** [comment]
Thanks for reporting back. 
Closing issue.
