### ISSUE TITLE
Fast Wallet

### ISSUE THREAD

**Issue by iqbiz** [coinables/coinables.github.io#3]
HI sir how are you. I saw your video on youtube. I want to know that can we cancel btc unconfirmed TX without RBF n fast wallet. 2nd if we spend unconfirmed BTC and send to other wallet than that receiving wallet will receive it as PARENT or RBF or totally free from RBF and PARNET. Also please tell me how to cancel btc unconfirmed TX without RBF

**Comment by iqbiz** [comment]
Sir i tried that fast wallet but when i sent unconfirmed BTC to other wallet they were PARENT. Not clear from RBF and PARENT. Sir can you guide or make video that how to cancel BTC unconfirmed Transaction without RBF protocol?

**Comment by coinables** [comment]
Do you mean how to double spend using replace by fee? The wallet was not built with the intention to double spend however you could do it as a First-Seen-Safe Replace-By-Fee if your transaction gets stuck and you need to increase the fee. Open up fastwallet in two different tabs, prepare your initial transaction in one tab BUT DON'T CLICK SEND just get it ready. Then in the other tab create another transaction using the same source funds but with a higher fee. Go back to first tab and click send, then you return to second tab and spend the same UTXO again.

**Comment by iqbiz** [comment]
thank you very much sir for your kind reply means alot.
Sir actually i dont want to double spend all i want to know that how to cancel bitcoin unconfirmed transaction without RBF protocol. My wallet got hacked and btc was going infront of me and i was not able to cancel as it was not RBF since than i want to learn that how we can cancel bitcoin unconfirmed transaction without RBF Protocol. Any method for this or any wallet offering this feature?

**Comment by iqbiz** [comment]
Or any method in which i can cancel/reverse btc unconfirmed Transaction without RBF using higher fee etc.  
In double spend i make 1st tx using RBF and 2nd without RBF. But by any chance if 1st transaction receiver increase fee then in this case receiver of 1st transaction will get 1st seen and get btc?

**Comment by coinables** [comment]
There is no way to revoke or otherwise cancel an unconfirmed transaction. Once it's been broadcasted the signed transaction is in the mempool and can be included in a block by a miner. Now there are some very rare exceptions like when there are increased fees on the network, and you submit a transaction with a very low fee that will get "stuck" in the mempool. There is a default expiration time where transactions will drop out of the mempool after 336 hours (2 weeks).

**Comment by iqbiz** [comment]
Sir this means that cancelling or reversing BTC unconfirmed transaction without RBF is not possible. With RBF its possible.?

**Comment by iqbiz** [comment]
Above you shared the method from fast wallet in that method double spend is possible 1st tx with RBF and 2nd without RBF? and before mempool make the 1st transaction invalid we can increase the fee of 1st transaction and 2nd transaction without RBF gets invalid on mempool.
Is this method is possible?
